[project]
name = "mcp-dev"
version = "0.1.0"
description = "A working example of local MCP server development."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.11.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.12.2",
    "ruff>=0.12.5",
]
